# -*- coding: utf-8 -*-
"""IronOreMoistureContent(MobileNet).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VAyrTMOlc01xlSJZLESieUsTY325vuL
"""

# =====================================================================================
# CELL 1: PURE MOBILENET PIPELINE (ORIGINAL FULL-IMAGE PROCESS)
# Architecture: MobileNetV2 (Optimized for Edge-AI / Industrial Embedded Cameras)
# Features: Train/Val Plots, Confusion Matrix, CSV Metrics Export, AMP Speedup
# =====================================================================================

import os
import zipfile
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from torch.cuda.amp import autocast, GradScaler

try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

ZIP_PATH = "iron_ore_pellets.zip"
BASE_DIR = "dataset_raw"
SPLIT_DIR = "dataset_mobilenet"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. PREPROCESSING (Original Full-Image Process)
# -------------------------------------------------------------------------
def prepare_original_dataset():
    if not os.path.exists(ZIP_PATH): raise ValueError(f"[ERROR] '{ZIP_PATH}' not found!")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    with zipfile.ZipFile(ZIP_PATH, 'r') as z: z.extractall(BASE_DIR)

    all_files, labels = [], []
    norm_cls = {c.lower().replace(" ", ""): c for c in CLASSES}
    for root, dirs, files in os.walk(BASE_DIR):
        p_norm = os.path.basename(root).lower().replace(" ", "")
        imgs = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]
        if p_norm in norm_cls:
            all_files.extend([os.path.join(root, f) for f in imgs])
            labels.extend([norm_cls[p_norm]] * len(imgs))

    # 70% Train, 15% Val, 15% Test
    X_tr, X_temp, y_tr, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_te, y_val, y_te = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)
    for split, paths, lbls in zip(['train', 'val', 'test'], [X_tr, X_val, X_te], [y_tr, y_val, y_te]):
        for cls in CLASSES: os.makedirs(os.path.join(SPLIT_DIR, split, cls), exist_ok=True)
        for path, cls in zip(paths, lbls):
            shutil.copy2(path, os.path.join(SPLIT_DIR, split, cls, os.path.basename(path)))

train_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

class PelletDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir, self.transform = Path(root_dir), transform
        self.paths, self.labels = [], []
        for idx, cls in enumerate(CLASSES):
            d = self.root_dir / cls
            if d.exists():
                for f in os.listdir(d):
                    if f.lower().endswith(('.jpg', '.png', '.jpeg')):
                        self.paths.append(str(d/f)); self.labels.append(idx)
    def __len__(self): return len(self.paths)
    def __getitem__(self, idx): return self.transform(Image.open(self.paths[idx]).convert('RGB')), self.labels[idx]

# -------------------------------------------------------------------------
# 2. ARCHITECTURE: PURE MOBILENET-V2
# -------------------------------------------------------------------------
class PureMobileNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        # Load Pretrained MobileNetV2
        self.backbone = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)

        # MobileNet outputs 1280 features. We replace the classifier block.
        self.backbone.classifier = nn.Sequential(
            nn.Dropout(p=0.4, inplace=True),
            nn.Linear(1280, num_classes)
        )

    def forward(self, x):
        return self.backbone(x)

# -------------------------------------------------------------------------
# 3. TRAINING & METRICS TRACKING
# -------------------------------------------------------------------------
def train_and_evaluate():
    prepare_original_dataset()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Training Pure MobileNet on: {device}")

    # MobileNet is extremely memory efficient; batch size 64 is safe and fast
    tr_loader = DataLoader(PelletDataset(os.path.join(SPLIT_DIR, 'train'), train_tf), batch_size=64, shuffle=True, pin_memory=True, num_workers=2)
    val_loader = DataLoader(PelletDataset(os.path.join(SPLIT_DIR, 'val'), test_tf), batch_size=64, pin_memory=True, num_workers=2)
    te_loader = DataLoader(PelletDataset(os.path.join(SPLIT_DIR, 'test'), test_tf), batch_size=64)

    model = PureMobileNet(len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4) # Slightly higher LR for MobileNet
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)
    scaler = GradScaler()

    best_val_loss = float('inf')
    epochs = 30

    history_train_loss, history_val_loss = [], []
    history_train_acc, history_val_acc = [], []

    for epoch in range(epochs):
        model.train()
        tr_loss = 0.0
        train_preds, train_labels = [], []

        for imgs, lbls in tr_loader:
            imgs, lbls = imgs.to(device, non_blocking=True), lbls.to(device, non_blocking=True)
            optimizer.zero_grad()

            with autocast():
                out = model(imgs)
                loss = criterion(out, lbls)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            tr_loss += loss.item() * imgs.size(0)

            _, preds = torch.max(out, 1)
            train_preds.extend(preds.detach().cpu().numpy())
            train_labels.extend(lbls.detach().cpu().numpy())

        tr_loss /= len(tr_loader.dataset)
        tr_acc = accuracy_score(train_labels, train_preds)

        model.eval()
        val_loss, val_preds, val_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                with autocast():
                    out = model(imgs)
                    loss = criterion(out, lbls)
                val_loss += loss.item() * imgs.size(0)

                _, preds = torch.max(out, 1)
                val_preds.extend(preds.cpu().numpy()); val_labels.extend(lbls.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        val_acc = accuracy_score(val_labels, val_preds)
        scheduler.step(val_loss)

        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {tr_loss:.4f} (Acc: {tr_acc:.4f}) | Val Loss: {val_loss:.4f} (Acc: {val_acc:.4f})")

        history_train_loss.append(tr_loss); history_val_loss.append(val_loss)
        history_train_acc.append(tr_acc); history_val_acc.append(val_acc)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_pure_mobilenet.pt')

    # ==========================================================
    # CSV EXPORT
    # ==========================================================
    metrics_df = pd.DataFrame({
        'Epoch': range(1, epochs + 1),
        'Train_Loss': history_train_loss,
        'Val_Loss': history_val_loss,
        'Train_Accuracy': history_train_acc,
        'Val_Accuracy': history_val_acc
    })
    metrics_df.to_csv('training_metrics_mobilenet.csv', index=False)
    print("\n[INFO] Accuracy and Loss metrics saved to 'training_metrics_mobilenet.csv'.")

    if IN_COLAB:
        files.download('training_metrics_mobilenet.csv')
        files.download('best_pure_mobilenet.pt')

    # ==========================================================
    # PLOT 1: LOSS CURVE
    # ==========================================================
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, epochs + 1), history_train_loss, label='Training Loss', marker='o', color='royalblue')
    plt.plot(range(1, epochs + 1), history_val_loss, label='Validation Loss', marker='s', color='darkorange')
    plt.title('Training vs Validation Loss (Pure MobileNet)', fontsize=14, fontweight='bold')
    plt.xlabel('Epochs', fontsize=12); plt.ylabel('Cross-Entropy Loss', fontsize=12)
    plt.xticks(range(1, epochs + 1, 2))
    plt.legend(fontsize=12); plt.grid(True, linestyle='--', alpha=0.7); plt.tight_layout()
    plt.show()

    # ==========================================================
    # PLOT 2: ACCURACY CURVE
    # ==========================================================
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, epochs + 1), history_train_acc, label='Training Accuracy', marker='o', color='forestgreen')
    plt.plot(range(1, epochs + 1), history_val_acc, label='Validation Accuracy', marker='s', color='mediumorchid')
    plt.title('Training vs Validation Accuracy (Pure MobileNet)', fontsize=14, fontweight='bold')
    plt.xlabel('Epochs', fontsize=12); plt.ylabel('Accuracy', fontsize=12)
    plt.xticks(range(1, epochs + 1, 2))
    plt.legend(fontsize=12); plt.grid(True, linestyle='--', alpha=0.7); plt.tight_layout()
    plt.show()

    # ==========================================================
    # EVALUATION & CONFUSION MATRIX
    # ==========================================================
    print("\n[INFO] Evaluating on 224x224 Test Images...")
    model.load_state_dict(torch.load('best_pure_mobilenet.pt', map_location=device, weights_only=True))
    model.eval()
    test_preds, test_labels = [], []
    with torch.no_grad():
        for imgs, lbls in te_loader:
            test_preds.extend(torch.max(model(imgs.to(device)), 1)[1].cpu().numpy()); test_labels.extend(lbls.numpy())

    print("\n--- Classification Report (Pure MobileNet) ---")
    print(classification_report(test_labels, test_preds, target_names=CLASSES, zero_division=0))

    cm = confusion_matrix(test_labels, test_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('Pure MobileNet - Confusion Matrix', fontsize=14, fontweight='bold')
    plt.xlabel('Predicted Label', fontsize=12); plt.ylabel('True Label', fontsize=12)
    plt.tight_layout(); plt.show()

if __name__ == "__main__":
    train_and_evaluate()

# =====================================================================================
# CELL 2: INTERACTIVE INFERENCE (PURE MOBILENET)
# =====================================================================================

import os, torch, io, matplotlib.pyplot as plt, numpy as np
import torch.nn as nn
from PIL import Image
from torchvision import transforms, models
from google.colab import files

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

class PureMobileNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.backbone = models.mobilenet_v2()
        self.backbone.classifier = nn.Sequential(
            nn.Dropout(p=0.4, inplace=True),
            nn.Linear(1280, num_classes)
        )
    def forward(self, x): return self.backbone(x)

def predict_mobilenet():
    if not os.path.exists('best_pure_mobilenet.pt'):
        print("[ERROR] 'best_pure_mobilenet.pt' not found! Train the model first."); return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = PureMobileNet(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_pure_mobilenet.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    print("\n[READY] Please upload a full-size iron ore pellet image.")
    uploaded = files.upload()

    for filename, file_data in uploaded.items():
        original_img = Image.open(io.BytesIO(file_data)).convert('RGB')
        img_tensor = tf(original_img).unsqueeze(0).to(device)

        with torch.no_grad():
            from torch.cuda.amp import autocast
            with autocast():
                raw_logits = model(img_tensor)
                probabilities = nn.Softmax(dim=1)(raw_logits)[0]

            conf, pred_idx = torch.max(probabilities, 0)

        plt.figure(figsize=(6, 6))
        plt.imshow(original_img)
        plt.title(f"MobileNet Prediction: {CLASSES[pred_idx.item()]}\n(Softmax Confidence: {conf.item() * 100:.2f}%)", color='purple', fontweight='bold')
        plt.axis('off'); plt.show()

        print("\n--- Final Output ---")
        for i, c in enumerate(CLASSES): print(f"{c}: {probabilities[i].item() * 100:.2f}%")

predict_mobilenet()

# =====================================================================================
# CELL 3: FPS BENCHMARKING (PURE MOBILENET)
# =====================================================================================

import time, torch, numpy as np
from PIL import Image
from torchvision import transforms, models
import torch.nn as nn
from torch.cuda.amp import autocast

class PureMobileNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.backbone = models.mobilenet_v2()
        self.backbone.classifier = nn.Sequential(
            nn.Dropout(p=0.4, inplace=True),
            nn.Linear(1280, num_classes)
        )
    def forward(self, x): return self.backbone(x)

def benchmark_mobilenet(iterations=1000):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Benchmarking MobileNet Pipeline on: {device.type.upper()}")

    if not os.path.exists('best_pure_mobilenet.pt'):
        print("[ERROR] 'best_pure_mobilenet.pt' not found."); return

    model = PureMobileNet(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_pure_mobilenet.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    dummy_image = Image.fromarray(np.random.randint(0, 255, (494, 659, 3), dtype=np.uint8))

    print("[INFO] Warming up GPU with Mixed Precision...")
    for _ in range(50):
        dummy_tensor = tf(dummy_image).unsqueeze(0).to(device)
        with torch.no_grad():
            with autocast(): _ = model(dummy_tensor)

    print(f"[INFO] Running {iterations} iterations on MobileNet Pipeline...\n")

    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            img_tensor = tf(dummy_image).unsqueeze(0).to(device)

            with autocast():
                probs = nn.Softmax(dim=1)(model(img_tensor))

            if device.type == 'cuda': torch.cuda.synchronize()
            pipeline_times.append((time.perf_counter() - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    print("="*60)
    print("         PURE MOBILENET SPEED REPORT")
    print("="*60)
    print(f"Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print(f"Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)

benchmark_mobilenet()