# -*- coding: utf-8 -*-
"""Segmented-CNN-ReLU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vWN2I7SZnB7i5Uq8ormm0bXV9oc9UYc
"""

# =====================================================================================
# CELL 1: QUADRANT SEGMENTATION & PURE CNN TRAINING (LOSS CURVE + CONFUSION MATRIX)
# Preprocessing: Resize to 656x480 -> 4x Quadrants (328x240)
# Architecture: 4-Layer Pure CNN
# =====================================================================================

import os
import zipfile
import shutil
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

ZIP_PATH = "iron_ore_pellets.zip"
BASE_DIR = "dataset_raw"
SPLIT_DIR = "dataset_quadrants"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. PREPROCESSING: RESIZE & SEGMENT PIPELINE
# -------------------------------------------------------------------------
def process_and_slice_images(file_paths, labels, split_name):
    for cls in CLASSES:
        os.makedirs(os.path.join(SPLIT_DIR, split_name, cls), exist_ok=True)

    for path, cls in zip(file_paths, labels):
        try:
            img = Image.open(path).convert('RGB')
            img_resized = img.resize((656, 480))
            quadrants = [
                img_resized.crop((0, 0, 328, 240)), img_resized.crop((328, 0, 656, 240)),
                img_resized.crop((0, 240, 328, 480)), img_resized.crop((328, 240, 656, 480))
            ]
            base_name = os.path.splitext(os.path.basename(path))[0]
            for i, q_img in enumerate(quadrants):
                q_img.save(os.path.join(SPLIT_DIR, split_name, cls, f"{base_name}_q{i}.jpg"))
        except Exception:
            pass

def prepare_quadrant_dataset():
    if not os.path.exists(ZIP_PATH): raise ValueError(f"[ERROR] '{ZIP_PATH}' not found!")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    with zipfile.ZipFile(ZIP_PATH, 'r') as z: z.extractall(BASE_DIR)

    all_files, labels = [], []
    norm_classes = {c.lower().replace(" ", ""): c for c in CLASSES}
    for root, dirs, files in os.walk(BASE_DIR):
        p_norm = os.path.basename(root).lower().replace(" ", "")
        imgs = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]
        if p_norm in norm_classes:
            all_files.extend([os.path.join(root, f) for f in imgs])
            labels.extend([norm_classes[p_norm]] * len(imgs))

    X_tr, X_temp, y_tr, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_te, y_val, y_te = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)
    process_and_slice_images(X_tr, y_tr, 'train')
    process_and_slice_images(X_val, y_val, 'val')
    process_and_slice_images(X_te, y_te, 'test')

train_tf = transforms.Compose([transforms.RandomHorizontalFlip(), transforms.RandomVerticalFlip(), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
test_tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

class QuadrantDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir, self.transform = Path(root_dir), transform
        self.paths, self.labels = [], []
        for idx, cls in enumerate(CLASSES):
            d = self.root_dir / cls
            if d.exists():
                for f in os.listdir(d):
                    if f.lower().endswith('.jpg'):
                        self.paths.append(str(d / f)); self.labels.append(idx)
    def __len__(self): return len(self.paths)
    def __getitem__(self, idx): return self.transform(Image.open(self.paths[idx]).convert('RGB')), self.labels[idx]

# -------------------------------------------------------------------------
# 2. ARCHITECTURE
# -------------------------------------------------------------------------
class QuadrantCNN(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.layer1 = nn.Sequential(nn.Conv2d(3, 32, 3, padding='same'), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2))
        self.layer2 = nn.Sequential(nn.Conv2d(32, 64, 3, padding='same'), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2))
        self.layer3 = nn.Sequential(nn.Conv2d(64, 128, 3, padding='same'), nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2))
        self.layer4 = nn.Sequential(nn.Conv2d(128, 256, 3, padding='same'), nn.BatchNorm2d(256), nn.ReLU(), nn.AdaptiveAvgPool2d((2, 2)))
        self.flatten = nn.Flatten()
        self.fc = nn.Sequential(nn.Linear(256 * 2 * 2, 512), nn.BatchNorm1d(512), nn.ReLU(), nn.Dropout(0.4), nn.Linear(512, num_classes))

    def forward(self, x): return self.fc(self.flatten(self.layer4(self.layer3(self.layer2(self.layer1(x))))))

# -------------------------------------------------------------------------
# 3. TRAINING & EVALUATION
# -------------------------------------------------------------------------
def train_and_evaluate():
    prepare_quadrant_dataset()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Training Quadrant CNN on: {device}")

    tr_loader = DataLoader(QuadrantDataset(os.path.join(SPLIT_DIR, 'train'), train_tf), batch_size=32, shuffle=True)
    val_loader = DataLoader(QuadrantDataset(os.path.join(SPLIT_DIR, 'val'), test_tf), batch_size=32)
    te_loader = DataLoader(QuadrantDataset(os.path.join(SPLIT_DIR, 'test'), test_tf), batch_size=32)

    model = QuadrantCNN(len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)

    best_val_loss = float('inf')
    epochs = 100

    history_train_loss = []
    history_val_loss = []

    for epoch in range(epochs):
        model.train()
        tr_loss = 0.0
        for imgs, lbls in tr_loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            optimizer.zero_grad()
            loss = criterion(model(imgs), lbls)
            loss.backward()
            optimizer.step()
            tr_loss += loss.item() * imgs.size(0)

        tr_loss /= len(tr_loader.dataset)

        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                out = model(imgs)
                val_loss += criterion(out, lbls).item() * imgs.size(0)
                all_preds.extend(torch.max(out, 1)[1].cpu().numpy()); all_labels.extend(lbls.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        scheduler.step(val_loss)
        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {tr_loss:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {accuracy_score(all_labels, all_preds):.4f}")

        history_train_loss.append(tr_loss)
        history_val_loss.append(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_quadrant_cnn.pt')

    # ==========================================================
    # 1. PLOT TRAINING VS VALIDATION LOSS
    # ==========================================================
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, epochs + 1), history_train_loss, label='Training Loss', marker='o', color='royalblue')
    plt.plot(range(1, epochs + 1), history_val_loss, label='Validation Loss', marker='s', color='darkorange')
    plt.title('Training Loss vs Validation Loss (Quadrant CNN)', fontsize=14, fontweight='bold')
    plt.xlabel('Epochs', fontsize=12)
    plt.ylabel('Cross-Entropy Loss', fontsize=12)
    plt.xticks(range(1, epochs + 1, 2))
    plt.legend(fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    # ==========================================================
    # 2. EVALUATE ON TEST SET & PRINT CLASSIFICATION REPORT
    # ==========================================================
    print("\n[INFO] Evaluating on 328x240 Test Quadrants...")
    model.load_state_dict(torch.load('best_quadrant_cnn.pt', map_location=device, weights_only=True))
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for imgs, lbls in te_loader:
            all_preds.extend(torch.max(model(imgs.to(device)), 1)[1].cpu().numpy()); all_labels.extend(lbls.numpy())

    print("\n--- Classification Report (Quadrant CNN) ---")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, zero_division=0))

    # ==========================================================
    # 3. PLOT CONFUSION MATRIX
    # ==========================================================
    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('Quadrant CNN Moisture Content - Confusion Matrix', fontsize=14, fontweight='bold')
    plt.xlabel('Predicted Label', fontsize=12)
    plt.ylabel('True Label', fontsize=12)
    plt.tight_layout()
    plt.show()

    if IN_COLAB: files.download('best_quadrant_cnn.pt')

if __name__ == "__main__":
    train_and_evaluate()

# =====================================================================================
# CELL 2: INTERACTIVE INFERENCE (ENSEMBLE QUADRANT CNN)
# Upload full image -> Splits to 4 -> Processes all 4 -> Averages Softmax Probabilities
# =====================================================================================

import os, torch, io, matplotlib.pyplot as plt, numpy as np
import torch.nn as nn
from PIL import Image
from torchvision import transforms
from google.colab import files

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

class QuadrantCNN(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.layer1 = nn.Sequential(nn.Conv2d(3, 32, 3, padding='same'), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2))
        self.layer2 = nn.Sequential(nn.Conv2d(32, 64, 3, padding='same'), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2))
        self.layer3 = nn.Sequential(nn.Conv2d(64, 128, 3, padding='same'), nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2))
        self.layer4 = nn.Sequential(nn.Conv2d(128, 256, 3, padding='same'), nn.BatchNorm2d(256), nn.ReLU(), nn.AdaptiveAvgPool2d((2, 2)))
        self.flatten = nn.Flatten()
        self.fc = nn.Sequential(nn.Linear(256 * 2 * 2, 512), nn.BatchNorm1d(512), nn.ReLU(), nn.Dropout(0.4), nn.Linear(512, num_classes))

    def forward(self, x): return self.fc(self.flatten(self.layer4(self.layer3(self.layer2(self.layer1(x))))))

def predict_quadrant_ensemble():
    if not os.path.exists('best_quadrant_cnn.pt'):
        print("[ERROR] 'best_quadrant_cnn.pt' not found!"); return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = QuadrantCNN(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_quadrant_cnn.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    print("\n[READY] Please upload a full-size iron ore pellet image.")
    uploaded = files.upload()

    for filename, file_data in uploaded.items():
        original_img = Image.open(io.BytesIO(file_data)).convert('RGB')

        # 1. Resize and Crop into 4 Pieces
        img_resized = original_img.resize((656, 480))
        quads = [
            img_resized.crop((0, 0, 328, 240)), img_resized.crop((328, 0, 656, 240)),
            img_resized.crop((0, 240, 328, 480)), img_resized.crop((328, 240, 656, 480))
        ]

        # 2. Batch them together: shape becomes [4, 3, 240, 328]
        batch_tensors = torch.stack([tf(q) for q in quads]).to(device)

        with torch.no_grad():
            raw_logits = model(batch_tensors) # Run inference on all 4 simultaneously!

            # Apply Softmax to all 4 quadrants individually
            quad_probs = nn.Softmax(dim=1)(raw_logits)

            # Ensemble: Average the probabilities across the 4 quadrants
            final_probs = torch.mean(quad_probs, dim=0)

            conf, pred_idx = torch.max(final_probs, 0)

        plt.figure(figsize=(6, 6))
        plt.imshow(original_img)
        plt.title(f"Ensemble Prediction: {CLASSES[pred_idx.item()]}\n(Average Softmax Confidence: {conf.item() * 100:.2f}%)", color='blue', fontweight='bold')
        plt.axis('off'); plt.show()

        print("\n--- Final Ensemble Output (Average of 4 Quadrants) ---")
        for i, c in enumerate(CLASSES): print(f"{c}: {final_probs[i].item() * 100:.2f}%")

predict_quadrant_ensemble()

# =====================================================================================
# CELL 3: FPS BENCHMARKING (QUADRANT PIPELINE)
# Evaluates latency including the segmentation pipeline
# =====================================================================================

import time, torch, numpy as np
from PIL import Image
from torchvision import transforms
import torch.nn as nn

def benchmark_quadrant_cnn(iterations=500):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Benchmarking Quadrant CNN Pipeline on: {device.type.upper()}")

    if not os.path.exists('best_quadrant_cnn.pt'):
        print("[ERROR] 'best_quadrant_cnn.pt' not found."); return

    model = QuadrantCNN(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_quadrant_cnn.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
    dummy_image = Image.fromarray(np.random.randint(0, 255, (494, 659, 3), dtype=np.uint8)) # Simulating original size

    print("[INFO] Warming up GPU...")
    for _ in range(20):
        dummy_batch = torch.randn(4, 3, 240, 328).to(device)
        with torch.no_grad(): _ = model(dummy_batch)

    print(f"[INFO] Running {iterations} iterations on End-to-End Segmentation Pipeline...\n")

    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            # 1. Resize & Crop Pipeline
            img_res = dummy_image.resize((656, 480))
            quads = [img_res.crop((0,0,328,240)), img_res.crop((328,0,656,240)), img_res.crop((0,240,328,480)), img_res.crop((328,240,656,480))]

            # 2. Tensor Batching
            batch_tensors = torch.stack([tf(q) for q in quads]).to(device)

            # 3. AI Inference & Softmax Ensembling
            probs = torch.mean(nn.Softmax(dim=1)(model(batch_tensors)), dim=0)

            if device.type == 'cuda': torch.cuda.synchronize()
            pipeline_times.append((time.perf_counter() - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    print("="*60)
    print("         QUADRANT CNN SPEED REPORT")
    print("="*60)
    print(f"Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print(" (Includes Resize -> 4x Crop -> 4x AI Passes -> Ensemble Avg)")
    print(f"Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)

benchmark_quadrant_cnn()