# -*- coding: utf-8 -*-
"""IronOreMoistureContent(EfficientNet-B5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13g3_6S4ikVFQLj4VFatiXeKeOmiYu0SD
"""

# =====================================================================================
# CELL 1: MAIN TRAINING PIPELINE
# Architecture: Dual-Stream EfficientNet-B5 + CBAM + MLBP Feature Fusion
# Framework: PyTorch | Target: Google Colab
# =====================================================================================

import os
import cv2
import zipfile
import shutil
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

ZIP_PATH = "iron_ore_pellets.zip"
BASE_DIR = "dataset_raw"
SPLIT_DIR = "dataset"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. DATASET EXTRACTION
# -------------------------------------------------------------------------
def prepare_dataset_hierarchy():
    if not os.path.exists(ZIP_PATH):
        raise ValueError(f"[ERROR] '{ZIP_PATH}' not found in the current directory!")

    print("[INFO] Unzipping dataset programmatically...")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    os.makedirs(BASE_DIR)

    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(BASE_DIR)

    all_files, labels = [], []
    normalized_classes = {c.lower().replace(" ", ""): c for c in CLASSES}

    for root, dirs, files in os.walk(BASE_DIR):
        parent_folder_raw = os.path.basename(root)
        parent_folder_norm = parent_folder_raw.lower().replace(" ", "")

        img_files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp'))]

        if parent_folder_norm in normalized_classes:
            actual_class = normalized_classes[parent_folder_norm]
            valid_files = [os.path.join(root, f) for f in img_files]
            all_files.extend(valid_files)
            labels.extend([actual_class] * len(valid_files))

    if len(all_files) == 0:
        raise ValueError(f"[ERROR] No valid images found matching the class folders {CLASSES}.")

    X_train, X_temp, y_train, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    print(f"[INFO] Successfully found and mapped {len(all_files)} images!")
    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)

    for split, paths, lbls in zip(['train', 'val', 'test'], [X_train, X_val, X_test], [y_train, y_val, y_test]):
        for cls in CLASSES: os.makedirs(os.path.join(SPLIT_DIR, split, cls), exist_ok=True)
        for path, cls in zip(paths, lbls):
            shutil.copy2(path, os.path.join(SPLIT_DIR, split, cls, os.path.basename(path)))

train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# -------------------------------------------------------------------------
# 2. ARCHITECTURE (EFFICIENTNET-B5)
# -------------------------------------------------------------------------
def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    kernel = np.ones((3, 3), np.float32) / 9.0
    mean_tau = cv2.filter2D(img_float, -1, kernel)

    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)

    dx = [-1,  0,  1, 1, 1, 0, -1, -1]
    dy = [-1, -1, -1, 0, 1, 1,  1,  0]

    for i in range(8):
        y1, y2 = 1 + dy[i], 1 + dy[i] + h
        x1, x2 = 1 + dx[i], 1 + dx[i] + w
        neighbor = padded[y1:y2, x1:x2]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)

    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    hist_float = hist.astype(np.float32)
    return hist_float / (hist_float.sum() + 1e-6)

class PelletDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir, self.transform = Path(root_dir), transform
        self.image_paths, self.labels = [], []
        valid_ext = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp')

        for idx, cls in enumerate(CLASSES):
            cls_dir = self.root_dir / cls
            if cls_dir.exists():
                for file_name in os.listdir(cls_dir):
                    if file_name.lower().endswith(valid_ext):
                        self.image_paths.append(str(cls_dir / file_name)); self.labels.append(idx)

    def __len__(self): return len(self.image_paths)
    def __getitem__(self, idx):
        image_pil = Image.open(self.image_paths[idx]).convert('RGB')
        img_tensor = self.transform(image_pil)

        img_cv_gray = cv2.resize(cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_vec = compute_mlbp(img_cv_gray)
        # Force float32 to prevent PyTorch type mismatch
        mlbp_tensor = torch.tensor(mlbp_vec, dtype=torch.float32)
        return img_tensor, mlbp_tensor, self.labels[idx]

class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False), nn.ReLU(), nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False))
        self.sigmoid = nn.Sigmoid()
    def forward(self, x): return self.sigmoid(self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x)))

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        return self.sigmoid(self.conv(torch.cat([avg_out, max_out], dim=1)))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca, self.sa = ChannelAttention(channels), SpatialAttention()
    def forward(self, x):
        x = self.ca(x) * x
        return self.sa(x) * x

class EfficientNetB5FusionNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        # B5 Outputs 2048 Channels natively
        self.features = models.efficientnet_b5(weights=models.EfficientNet_B5_Weights.IMAGENET1K_V1).features
        self.cbam = CBAM(2048)
        self.global_pool = nn.AdaptiveAvgPool2d(1)

        # 2048 (Global) + 256 (Local MLBP) = 2304 Total Features
        self.classifier = nn.Sequential(
            nn.Linear(2048 + 256, 512),
            nn.BatchNorm1d(512),
            nn.SiLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        f_global = torch.flatten(self.global_pool(self.cbam(self.features(img))), 1)
        return self.classifier(torch.cat([f_global, mlbp], dim=1))

# -------------------------------------------------------------------------
# 3. TRAINING & EVALUATION
# -------------------------------------------------------------------------
def train_and_evaluate():
    prepare_dataset_hierarchy()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Accelerating computation on: {device}")

    train_data = PelletDataset(os.path.join(SPLIT_DIR, 'train'), transform=train_transforms)
    val_data = PelletDataset(os.path.join(SPLIT_DIR, 'val'), transform=test_transforms)
    test_data = PelletDataset(os.path.join(SPLIT_DIR, 'test'), transform=test_transforms)

    # STRICT Batch Size Limit: 16 to prevent B5 from OOM crashing
    batch_size = 16
    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_data, batch_size=batch_size, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=False)

    model = EfficientNetB5FusionNet(num_classes=len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)

    epochs = 30
    best_val_loss = float('inf')

    print("\n[INFO] Initializing EfficientNet-B5 Dual-Stream Training...")

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for imgs, mlbps, labels in train_loader:
            imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(imgs, mlbps), labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * imgs.size(0)

        train_loss /= len(train_loader.dataset)

        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, mlbps, labels in val_loader:
                imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
                outputs = model(imgs, mlbps)
                loss = criterion(outputs, labels)
                val_loss += loss.item() * imgs.size(0)

                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy()); all_labels.extend(labels.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        scheduler.step(val_loss)
        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {accuracy_score(all_labels, all_preds):.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_effnet_b5.pt')

    print("\n[INFO] Training Complete. Best model saved as 'best_effnet_b5.pt'")
    if IN_COLAB: files.download('best_effnet_b5.pt')

    # EVALUATION
    model.load_state_dict(torch.load('best_effnet_b5.pt', map_location=device, weights_only=True))
    model.eval()
    all_preds, all_labels = [], []
    print("\n[INFO] Evaluating on Test Split...")

    with torch.no_grad():
        for imgs, mlbps, labels in test_loader:
            imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
            _, preds = torch.max(model(imgs, mlbps), 1)
            all_preds.extend(preds.cpu().numpy()); all_labels.extend(labels.cpu().numpy())

    print("\n--- Classification Report (EfficientNet-B5) ---")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, zero_division=0))

    plt.figure(figsize=(8, 6))
    sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('EfficientNet-B5 Moisture Content - Confusion Matrix')
    plt.xlabel('Predicted Label'); plt.ylabel('True Label'); plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    train_and_evaluate()

# =====================================================================================
# CELL 2: INTERACTIVE INFERENCE PIPELINE (EFFICIENTNET-B5)
# =====================================================================================

import os, cv2, torch, io, numpy as np, matplotlib.pyplot as plt
import torch.nn as nn
from PIL import Image
from torchvision import transforms, models
from google.colab import files

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    mean_tau = cv2.filter2D(img_float, -1, np.ones((3, 3), np.float32) / 9.0)
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)
    dx, dy = [-1,  0,  1, 1, 1, 0, -1, -1], [-1, -1, -1, 0, 1, 1,  1,  0]
    for i in range(8):
        neighbor = padded[1+dy[i]:1+dy[i]+h, 1+dx[i]:1+dx[i]+w]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)
    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    return hist.astype(np.float32) / (hist.sum() + 1e-6)

class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super().__init__()
        self.avg_pool, self.max_pool = nn.AdaptiveAvgPool2d(1), nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False), nn.ReLU(), nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False))
        self.sigmoid = nn.Sigmoid()
    def forward(self, x): return self.sigmoid(self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x)))

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x): return self.sigmoid(self.conv(torch.cat([torch.mean(x, 1, keepdim=True), torch.max(x, 1, keepdim=True)[0]], 1)))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca, self.sa = ChannelAttention(channels), SpatialAttention()
    def forward(self, x): return self.sa(self.ca(x) * x) * (self.ca(x) * x)

class EfficientNetB5FusionNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.features = models.efficientnet_b5().features
        self.cbam = CBAM(2048) # B5 depth
        self.global_pool = nn.AdaptiveAvgPool2d(1)
        self.classifier = nn.Sequential(nn.Linear(2048 + 256, 512), nn.BatchNorm1d(512), nn.SiLU(), nn.Dropout(0.4), nn.Linear(512, num_classes))

    def forward(self, img, mlbp):
        return self.classifier(torch.cat([torch.flatten(self.global_pool(self.cbam(self.features(img))), 1), mlbp], dim=1))

def predict_interactive_b5():
    if not os.path.exists('best_effnet_b5.pt'):
        print("[ERROR] 'best_effnet_b5.pt' not found! Train the B5 model first."); return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Loading EfficientNet-B5 Model on {device}...")

    model = EfficientNetB5FusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_effnet_b5.pt', map_location=device, weights_only=True))
    model.eval()

    transform = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    print("\n[READY] Please upload an iron ore pellet image.")
    uploaded = files.upload()

    for filename, file_data in uploaded.items():
        image_pil = Image.open(io.BytesIO(file_data)).convert('RGB')
        img_tensor = transform(image_pil).unsqueeze(0).to(device)

        img_cv_gray = cv2.resize(cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_tensor = torch.tensor(compute_mlbp(img_cv_gray), dtype=torch.float32).unsqueeze(0).to(device)

        with torch.no_grad():
            outputs = model(img_tensor, mlbp_tensor)
            probs = torch.nn.functional.softmax(outputs, dim=1)[0]
            conf, pred_idx = torch.max(probs, 0)

        plt.figure(figsize=(6, 6))
        plt.imshow(image_pil)
        plt.title(f"B5 Prediction: {CLASSES[pred_idx.item()]}\n(Confidence: {conf.item() * 100:.2f}%)", color='darkblue', fontweight='bold')
        plt.axis('off'); plt.show()

        print("\n--- Class Probabilities ---")
        for i, c in enumerate(CLASSES): print(f"{c}: {probs[i].item() * 100:.2f}%")

predict_interactive_b5()

# =====================================================================================
# CELL 3: FPS BENCHMARKING (EFFICIENTNET-B5)
# =====================================================================================

import time, torch, cv2, numpy as np
from PIL import Image
from torchvision import transforms

def benchmark_inference_b5(iterations=100):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Benchmarking EfficientNet-B5 on: {device.type.upper()}")

    if not os.path.exists('best_effnet_b5.pt'):
        print("[ERROR] 'best_effnet_b5.pt' not found."); return

    # Relies on the model architecture defined in Cell 2
    model = EfficientNetB5FusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_effnet_b5.pt', map_location=device, weights_only=True))
    model.eval()

    transform = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
    dummy_image = Image.fromarray(np.random.randint(0, 255, (300, 300, 3), dtype=np.uint8))

    print("[INFO] Warming up GPU (10 passes)...")
    for _ in range(10):
        i_tensor = transform(dummy_image).unsqueeze(0).to(device)
        i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
        m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)
        with torch.no_grad(): _ = model(i_tensor, m_tensor)

    print(f"[INFO] Warm-up complete. Running {iterations} iterations...\n")

    # TEST 1: Pure GPU AI Bound
    i_tensor = transform(dummy_image).unsqueeze(0).to(device)
    i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
    m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)

    model_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()
            _ = model(i_tensor, m_tensor)
            if device.type == 'cuda': torch.cuda.synchronize()
            model_times.append((time.perf_counter() - t_start) * 1000)

    avg_model_time = np.mean(model_times)

    # TEST 2: CPU + GPU End-to-End Pipeline
    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            i_t = transform(dummy_image).unsqueeze(0).to(device)
            i_c = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
            m_t = torch.tensor(compute_mlbp(i_c), dtype=torch.float32).unsqueeze(0).to(device)
            _ = model(i_t, m_t)

            if device.type == 'cuda': torch.cuda.synchronize()
            pipeline_times.append((time.perf_counter() - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    print("="*60)
    print("         EFFICIENTNET-B5 INFERENCE SPEED REPORT")
    print("="*60)
    print(f"1. Pure AI Model Latency : {avg_model_time:.2f} ms / frame")
    print(f"   Max Theoretical Speed : {1000/avg_model_time:.1f} FPS")
    print("-" * 60)
    print(f"2. Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print("   (Includes Image Prep + MLBP CPU Math + AI Forward Pass)")
    print(f"   Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)

benchmark_inference_b5()