# -*- coding: utf-8 -*-
"""IronOreMoistureContent(EfficientNet-B2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Wy4w5NPV6HNHvV-h-JxEb0UbaQqkM3D
"""

# =====================================================================================
# Moisture Content Recognition Model Integrating Image Texture Features
# Architecture: Dual-Stream EfficientNet-B2 + CBAM + MLBP Feature Fusion
# Framework: PyTorch | Target: Google Colab
# =====================================================================================

import os
import cv2
import zipfile
import shutil
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Graceful Colab detection for automatic downloading
try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# =====================================================================================
# PART 1: ROBUST DATASET EXTRACTION & PREPROCESSING
# =====================================================================================

ZIP_PATH = "iron_ore_pellets.zip"
BASE_DIR = "dataset_raw"
SPLIT_DIR = "dataset"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

def prepare_dataset_hierarchy():
    """Unzips and enforces splits. Forgiving to case-sensitivity, spaces, and formats."""
    if not os.path.exists(ZIP_PATH):
        raise ValueError(f"[ERROR] '{ZIP_PATH}' not found in the current directory!")

    print("[INFO] Unzipping dataset programmatically...")
    if os.path.exists(BASE_DIR):
        shutil.rmtree(BASE_DIR)
    os.makedirs(BASE_DIR)

    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(BASE_DIR)

    all_files, labels = [], []
    normalized_classes = {c.lower().replace(" ", ""): c for c in CLASSES}

    for root, dirs, files in os.walk(BASE_DIR):
        parent_folder_raw = os.path.basename(root)
        parent_folder_norm = parent_folder_raw.lower().replace(" ", "")

        img_files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp'))]

        if parent_folder_norm in normalized_classes:
            actual_class = normalized_classes[parent_folder_norm]
            valid_files = [os.path.join(root, f) for f in img_files]
            all_files.extend(valid_files)
            labels.extend([actual_class] * len(valid_files))

    if len(all_files) == 0:
        raise ValueError(f"[ERROR] No valid images found matching the class folders {CLASSES}.")

    # Stratified Splits: 70% Train, 15% Val, 15% Test
    X_train, X_temp, y_train, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    print(f"[INFO] Successfully found and mapped {len(all_files)} images!")
    if os.path.exists(SPLIT_DIR):
        shutil.rmtree(SPLIT_DIR)

    for split, paths, lbls in zip(['train', 'val', 'test'], [X_train, X_val, X_test], [y_train, y_val, y_test]):
        for cls in CLASSES:
            os.makedirs(os.path.join(SPLIT_DIR, split, cls), exist_ok=True)
        for path, cls in zip(paths, lbls):
            shutil.copy2(path, os.path.join(SPLIT_DIR, split, cls, os.path.basename(path)))

# Image Transformations
train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# =====================================================================================
# PART 2: MLBP & EFFICIENTNET-B2 ARCHITECTURE
# =====================================================================================

def compute_mlbp(image_cv_gray):
    """Computes Modified Local Binary Pattern (MLBP) yielding a 256-D vector."""
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)

    # Adaptive threshold tau based on 3x3 neighborhood
    kernel = np.ones((3, 3), np.float32) / 9.0
    mean_tau = cv2.filter2D(img_float, -1, kernel)

    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)

    dx = [-1,  0,  1, 1, 1, 0, -1, -1]
    dy = [-1, -1, -1, 0, 1, 1,  1,  0]

    for i in range(8):
        y1, y2 = 1 + dy[i], 1 + dy[i] + h
        x1, x2 = 1 + dx[i], 1 + dx[i] + w
        neighbor = padded[y1:y2, x1:x2]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)

    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))

    # Ensure float32 return to prevent tensor dtype mismatches
    hist_float = hist.astype(np.float32)
    return hist_float / (hist_float.sum() + 1e-6)

class PelletDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = Path(root_dir)
        self.transform = transform
        self.image_paths, self.labels = [], []
        valid_ext = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp')

        for idx, cls in enumerate(CLASSES):
            cls_dir = self.root_dir / cls
            if cls_dir.exists():
                for file_name in os.listdir(cls_dir):
                    if file_name.lower().endswith(valid_ext):
                        self.image_paths.append(str(cls_dir / file_name))
                        self.labels.append(idx)

    def __len__(self): return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image_pil = Image.open(img_path).convert('RGB')

        # 1. Global Image Tensor
        img_tensor = self.transform(image_pil)

        # 2. Local MLBP Tensor
        img_cv_gray = cv2.resize(cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_vec = compute_mlbp(img_cv_gray)
        # EXPLICITLY set dtype to float32 to fix the Double/Float RuntimeError
        mlbp_tensor = torch.tensor(mlbp_vec, dtype=torch.float32)

        return img_tensor, mlbp_tensor, self.labels[idx]

class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False),
            nn.ReLU(),
            nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x)))

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        return self.sigmoid(self.conv(torch.cat([avg_out, max_out], dim=1)))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca = ChannelAttention(channels)
        self.sa = SpatialAttention()

    def forward(self, x):
        x = self.ca(x) * x
        return self.sa(x) * x

class EfficientNetB2FusionNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()

        # Backbone: EfficientNet-B2 (Outputs 1408 Channels)
        efficientnet_b2 = models.efficientnet_b2(weights=models.EfficientNet_B2_Weights.IMAGENET1K_V1)
        self.features = efficientnet_b2.features

        # Attention Modules
        self.cbam = CBAM(1408)
        self.global_pool = nn.AdaptiveAvgPool2d(1)

        # Fusion Classifier (1408 Global + 256 Local MLBP = 1664 Total Features)
        self.classifier = nn.Sequential(
            nn.Linear(1408 + 256, 512),
            nn.BatchNorm1d(512),
            nn.SiLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        f_global = self.features(img)
        f_global = self.cbam(f_global)
        f_global = self.global_pool(f_global)
        f_global = torch.flatten(f_global, 1)

        f_fused = torch.cat([f_global, mlbp], dim=1)
        return self.classifier(f_fused)

# =====================================================================================
# PART 3: TRAINING LOOP
# =====================================================================================

def train_model():
    prepare_dataset_hierarchy()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Accelerating computation on: {device}")

    train_data = PelletDataset(os.path.join(SPLIT_DIR, 'train'), transform=train_transforms)
    val_data = PelletDataset(os.path.join(SPLIT_DIR, 'val'), transform=test_transforms)

    batch_size = 32 # B2 is lightweight enough for batch size 32 on a T4 GPU
    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_data, batch_size=batch_size, shuffle=False, num_workers=2)

    model = EfficientNetB2FusionNet(num_classes=len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)

    epochs = 30
    best_val_loss = float('inf')

    print("\n[INFO] Initializing EfficientNet-B2 Dual-Stream Training...")

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for imgs, mlbps, labels in train_loader:
            imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(imgs, mlbps), labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * imgs.size(0)

        train_loss /= len(train_loader.dataset)

        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, mlbps, labels in val_loader:
                imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
                outputs = model(imgs, mlbps)
                loss = criterion(outputs, labels)
                val_loss += loss.item() * imgs.size(0)

                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        val_acc = accuracy_score(all_labels, all_preds)

        scheduler.step(val_loss)
        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_effnet_b2.pt')

    print("\n[INFO] Training Complete. Best model saved as 'best_effnet_b2.pt'")
    if IN_COLAB:
        files.download('best_effnet_b2.pt')

# =====================================================================================
# PART 4: EVALUATION PIPELINE
# =====================================================================================

def evaluate_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    test_data = PelletDataset(os.path.join(SPLIT_DIR, 'test'), transform=test_transforms)
    test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

    model = EfficientNetB2FusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_effnet_b2.pt', map_location=device, weights_only=True))
    model.eval()

    all_preds, all_labels = [], []
    print("\n[INFO] Evaluating on Test Split...")

    with torch.no_grad():
        for imgs, mlbps, labels in test_loader:
            imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
            _, preds = torch.max(model(imgs, mlbps), 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    print("\n--- Classification Report (EfficientNet-B2) ---")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, zero_division=0))

    plt.figure(figsize=(8, 6))
    sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('EfficientNet-B2 Moisture Content - Confusion Matrix')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# =====================================================================================
# MAIN EXECUTION
# =====================================================================================
if __name__ == "__main__":
    train_model()
    evaluate_model()

# =====================================================================================
# CELL 1: INTERACTIVE INFERENCE PIPELINE (EFFICIENTNET-B2)
# Upload a custom image and get the Moisture Content Prediction
# =====================================================================================

import os
import cv2
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import transforms, models
from google.colab import files
import io

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. EFFICIENTNET-B2 ARCHITECTURE RECONSTRUCTION
# -------------------------------------------------------------------------
def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    kernel = np.ones((3, 3), np.float32) / 9.0
    mean_tau = cv2.filter2D(img_float, -1, kernel)
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)

    dx = [-1,  0,  1, 1, 1, 0, -1, -1]
    dy = [-1, -1, -1, 0, 1, 1,  1,  0]

    for i in range(8):
        y1, y2 = 1 + dy[i], 1 + dy[i] + h
        x1, x2 = 1 + dx[i], 1 + dx[i] + w
        neighbor = padded[y1:y2, x1:x2]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)

    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))

    # Strictly enforce float32
    hist_float = hist.astype(np.float32)
    return hist_float / (hist_float.sum() + 1e-6)

class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False),
            nn.ReLU(),
            nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x)))

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        return self.sigmoid(self.conv(torch.cat([avg_out, max_out], dim=1)))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca = ChannelAttention(channels)
        self.sa = SpatialAttention()

    def forward(self, x):
        x = self.ca(x) * x
        return self.sa(x) * x

class EfficientNetB2FusionNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        efficientnet = models.efficientnet_b2()
        self.features = efficientnet.features
        self.cbam = CBAM(1408) # B2 specific depth
        self.global_pool = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Linear(1408 + 256, 512),
            nn.BatchNorm1d(512),
            nn.SiLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        f_global = torch.flatten(self.global_pool(self.cbam(self.features(img))), 1)
        return self.classifier(torch.cat([f_global, mlbp], dim=1))

# -------------------------------------------------------------------------
# 2. INFERENCE & UPLOAD LOGIC
# -------------------------------------------------------------------------
def predict_interactive_b2():
    if not os.path.exists('best_effnet_b2.pt'):
        print("[ERROR] 'best_effnet_b2.pt' not found! Please ensure your trained B2 weights file is uploaded.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Loading EfficientNet-B2 Model on {device}...")

    model = EfficientNetB2FusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_effnet_b2.pt', map_location=device, weights_only=True))
    model.eval()

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    print("\n[READY] Please upload an iron ore pellet image for inference.")
    uploaded = files.upload()

    if not uploaded:
        print("[WARNING] No image uploaded.")
        return

    for filename, file_data in uploaded.items():
        try:
            image_pil = Image.open(io.BytesIO(file_data)).convert('RGB')

            # Prepare Global Stream
            img_tensor = transform(image_pil).unsqueeze(0).to(device)

            # Prepare Local Stream (Force float32 dtype)
            img_cv_gray = cv2.resize(cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY), (224, 224))
            mlbp_vec = compute_mlbp(img_cv_gray)
            mlbp_tensor = torch.tensor(mlbp_vec, dtype=torch.float32).unsqueeze(0).to(device)

            # AI Inference
            with torch.no_grad():
                outputs = model(img_tensor, mlbp_tensor)
                probabilities = torch.nn.functional.softmax(outputs, dim=1)[0]
                confidence, pred_idx = torch.max(probabilities, 0)

            pred_class = CLASSES[pred_idx.item()]
            conf_score = confidence.item() * 100

            # Plotting
            plt.figure(figsize=(6, 6))
            plt.imshow(image_pil)
            plt.title(f"EfficientNet-B2 Prediction: {pred_class}\n(Confidence: {conf_score:.2f}%)",
                      fontsize=14, color='darkblue', fontweight='bold')
            plt.axis('off')
            plt.show()

            print("\n--- Detailed Confidence Scores ---")
            for i, cls_name in enumerate(CLASSES):
                print(f"{cls_name}: {probabilities[i].item() * 100:.2f}%")

        except Exception as e:
            print(f"[ERROR] Failed to process image '{filename}'. Reason: {e}")

# Execute UI
predict_interactive_b2()

# =====================================================================================
# CELL 2: INFERENCE SPEED & FPS BENCHMARKING (EFFICIENTNET-B2)
# Evaluates latency for real-world mining hardware deployment
# =====================================================================================

import time
import torch
import cv2
import numpy as np
from PIL import Image
from torchvision import transforms

def benchmark_inference_b2(iterations=100):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Initializing EfficientNet-B2 benchmark on: {device.type.upper()}")

    if not os.path.exists('best_effnet_b2.pt'):
        print("[ERROR] 'best_effnet_b2.pt' not found! Cannot run benchmark.")
        return

    # Load Model (relies on class from Cell 1)
    model = EfficientNetB2FusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_effnet_b2.pt', map_location=device, weights_only=True))
    model.eval()

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # Create dummy frame representing camera feed
    dummy_image = Image.fromarray(np.random.randint(0, 255, (300, 300, 3), dtype=np.uint8))

    # ---------------------------------------------------------
    # HARDWARE WARMUP
    # ---------------------------------------------------------
    print("[INFO] Warming up hardware architecture (10 passes)...")
    for _ in range(10):
        i_tensor = transform(dummy_image).unsqueeze(0).to(device)
        i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
        m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)
        with torch.no_grad():
            _ = model(i_tensor, m_tensor)

    print(f"[INFO] Hardware warm-up complete. Benchmarking {iterations} iterations...\n")

    # ---------------------------------------------------------
    # TEST 1: PURE AI INFERENCE (GPU Bound)
    # ---------------------------------------------------------
    img_tensor = transform(dummy_image).unsqueeze(0).to(device)
    img_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
    mlbp_tensor = torch.tensor(compute_mlbp(img_cv), dtype=torch.float32).unsqueeze(0).to(device)

    model_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            _ = model(img_tensor, mlbp_tensor)

            if device.type == 'cuda': torch.cuda.synchronize()
            t_end = time.perf_counter()
            model_times.append((t_end - t_start) * 1000)

    avg_model_time = np.mean(model_times)

    # ---------------------------------------------------------
    # TEST 2: FULL END-TO-END PIPELINE (CPU + GPU Bound)
    # ---------------------------------------------------------
    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            # Simulated frame grab and processing
            i_tensor = transform(dummy_image).unsqueeze(0).to(device)
            i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
            # Force float32
            m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)

            _ = model(i_tensor, m_tensor)

            if device.type == 'cuda': torch.cuda.synchronize()
            t_end = time.perf_counter()
            pipeline_times.append((t_end - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    # ---------------------------------------------------------
    # REPORT GENERATION
    # ---------------------------------------------------------
    print("="*60)
    print("         EFFICIENTNET-B2 INFERENCE SPEED REPORT")
    print("="*60)
    print(f"1. Pure AI Model Latency : {avg_model_time:.2f} ms / frame")
    print(f"   Max Theoretical Speed : {1000/avg_model_time:.1f} FPS")
    print("-" * 60)
    print(f"2. Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print("   (Includes Image Prep + MLBP CPU Math + AI Forward Pass)")
    print(f"   Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)

# Execute Benchmark
benchmark_inference_b2()