# -*- coding: utf-8 -*-
"""IronOreMoisture(3 layer CNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_UEWw55r4DyPKoJWBUeT8_NUwDDm46s
"""

# =====================================================================================
# CELL 1: ENHANCED CUSTOM 3-LAYER CNN PIPELINE
# Architecture: 3x (Conv 3x3, stride=1, padding='same') + MLBP Fusion
# =====================================================================================

import os
import cv2
import zipfile
import shutil
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

ZIP_PATH = "iron_ore_pellets.zip"
BASE_DIR = "dataset_raw"
SPLIT_DIR = "dataset"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. DATASET & MLBP PREPARATION
# -------------------------------------------------------------------------
def prepare_dataset_hierarchy():
    if not os.path.exists(ZIP_PATH):
        raise ValueError(f"[ERROR] '{ZIP_PATH}' not found!")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    os.makedirs(BASE_DIR)
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref: zip_ref.extractall(BASE_DIR)

    all_files, labels = [], []
    normalized_classes = {c.lower().replace(" ", ""): c for c in CLASSES}
    for root, dirs, files in os.walk(BASE_DIR):
        p_norm = os.path.basename(root).lower().replace(" ", "")
        imgs = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]
        if p_norm in normalized_classes:
            actual_class = normalized_classes[p_norm]
            all_files.extend([os.path.join(root, f) for f in imgs])
            labels.extend([actual_class] * len(imgs))

    X_train, X_temp, y_train, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)
    for split, paths, lbls in zip(['train', 'val', 'test'], [X_train, X_val, X_test], [y_train, y_val, y_test]):
        for cls in CLASSES: os.makedirs(os.path.join(SPLIT_DIR, split, cls), exist_ok=True)
        for path, cls in zip(paths, lbls): shutil.copy2(path, os.path.join(SPLIT_DIR, split, cls, os.path.basename(path)))

def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    mean_tau = cv2.filter2D(img_float, -1, np.ones((3, 3), np.float32) / 9.0)
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)
    dx, dy = [-1,  0,  1, 1, 1, 0, -1, -1], [-1, -1, -1, 0, 1, 1,  1,  0]
    for i in range(8):
        neighbor = padded[1+dy[i]:1+dy[i]+h, 1+dx[i]:1+dx[i]+w]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)
    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    return (hist.astype(np.float32) / (hist.sum() + 1e-6))

class DualStreamPelletDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir, self.transform = Path(root_dir), transform
        self.image_paths, self.labels = [], []
        for idx, cls in enumerate(CLASSES):
            d = self.root_dir / cls
            if d.exists():
                for f in os.listdir(d):
                    if f.lower().endswith(('.jpg', '.png', '.jpeg', '.bmp')):
                        self.image_paths.append(str(d / f)); self.labels.append(idx)

    def __len__(self): return len(self.image_paths)
    def __getitem__(self, idx):
        img_pil = Image.open(self.image_paths[idx]).convert('RGB')
        img_tensor = self.transform(img_pil)
        img_cv_gray = cv2.resize(cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_tensor = torch.tensor(compute_mlbp(img_cv_gray), dtype=torch.float32)
        return img_tensor, mlbp_tensor, self.labels[idx]

train_tf = transforms.Compose([transforms.Resize((224, 224)), transforms.RandomHorizontalFlip(), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
test_tf = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

# -------------------------------------------------------------------------
# 2. UPGRADED 3-LAYER CNN (With Texture Fusion)
# -------------------------------------------------------------------------
class Enhanced3LayerCNN(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()

        # Layer 1: Wider filters (64)
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding='same'),
            nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(kernel_size=2)
        )
        # Layer 2: Wider filters (128)
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding='same'),
            nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(kernel_size=2)
        )
        # Layer 3: Wider filters (256)
        self.layer3 = nn.Sequential(
            nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding='same'),
            nn.BatchNorm2d(256), nn.ReLU(),
            nn.AdaptiveAvgPool2d((2, 2)) # Captures 4x more spatial resolution than before
        )

        # Fusion Classifier (256 * 2 * 2 = 1024 CNN features) + (256 MLBP features) = 1280 Total
        self.flatten = nn.Flatten()
        self.classifier = nn.Sequential(
            nn.Linear(1024 + 256, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.4), # Added dropout to prevent overfitting
            nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        # Image through 3-Layer CNN
        cnn_features = self.flatten(self.layer3(self.layer2(self.layer1(img))))
        # Fuse with MLBP
        fused = torch.cat([cnn_features, mlbp], dim=1)
        return self.classifier(fused)

# -------------------------------------------------------------------------
# 3. TRAINING & EVALUATION
# -------------------------------------------------------------------------
def train_and_evaluate():
    prepare_dataset_hierarchy()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Training Enhanced Custom CNN on: {device}")

    tr_loader = DataLoader(DualStreamPelletDataset(os.path.join(SPLIT_DIR, 'train'), train_tf), batch_size=32, shuffle=True)
    val_loader = DataLoader(DualStreamPelletDataset(os.path.join(SPLIT_DIR, 'val'), test_tf), batch_size=32)
    te_loader = DataLoader(DualStreamPelletDataset(os.path.join(SPLIT_DIR, 'test'), test_tf), batch_size=32)

    model = Enhanced3LayerCNN(len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=5e-4, weight_decay=1e-3)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)

    best_val_loss = float('inf')
    epochs = 30

    for epoch in range(epochs):
        model.train()
        tr_loss = 0.0
        for imgs, mlbps, lbls in tr_loader:
            imgs, mlbps, lbls = imgs.to(device), mlbps.to(device), lbls.to(device)
            optimizer.zero_grad()
            loss = criterion(model(imgs, mlbps), lbls)
            loss.backward()
            optimizer.step()
            tr_loss += loss.item() * imgs.size(0)

        tr_loss /= len(tr_loader.dataset)

        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, mlbps, lbls in val_loader:
                imgs, mlbps, lbls = imgs.to(device), mlbps.to(device), lbls.to(device)
                out = model(imgs, mlbps)
                val_loss += criterion(out, lbls).item() * imgs.size(0)
                all_preds.extend(torch.max(out, 1)[1].cpu().numpy()); all_labels.extend(lbls.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        scheduler.step(val_loss)
        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {tr_loss:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {accuracy_score(all_labels, all_preds):.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_custom_enhanced.pt')

    print("\n[INFO] Evaluating on Test Split...")
    model.load_state_dict(torch.load('best_custom_enhanced.pt', map_location=device, weights_only=True))
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for imgs, mlbps, lbls in te_loader:
            imgs, mlbps, lbls = imgs.to(device), mlbps.to(device), lbls.to(device)
            all_preds.extend(torch.max(model(imgs, mlbps), 1)[1].cpu().numpy()); all_labels.extend(lbls.cpu().numpy())

    print("\n--- Classification Report (Enhanced 3-Layer CNN) ---")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, zero_division=0))

    plt.figure(figsize=(8, 6))
    sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('Enhanced CNN Moisture Content - Confusion Matrix')
    plt.xlabel('Predicted Label'); plt.ylabel('True Label'); plt.tight_layout(); plt.show()

    if IN_COLAB: files.download('best_custom_enhanced.pt')

if __name__ == "__main__":
    train_and_evaluate()

# =====================================================================================
# CELL 2: INTERACTIVE INFERENCE (ENHANCED 3-LAYER CNN)
# Upload a custom image and get the Softmax Moisture Prediction
# =====================================================================================

import os, cv2, torch, io, matplotlib.pyplot as plt, numpy as np
import torch.nn as nn
from PIL import Image
from torchvision import transforms
from google.colab import files

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    mean_tau = cv2.filter2D(img_float, -1, np.ones((3, 3), np.float32) / 9.0)
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)
    dx, dy = [-1,  0,  1, 1, 1, 0, -1, -1], [-1, -1, -1, 0, 1, 1,  1,  0]
    for i in range(8):
        neighbor = padded[1+dy[i]:1+dy[i]+h, 1+dx[i]:1+dx[i]+w]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)
    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    return (hist.astype(np.float32) / (hist.sum() + 1e-6))

class Enhanced3LayerCNN(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.layer1 = nn.Sequential(nn.Conv2d(3, 64, 3, 1, 'same'), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2))
        self.layer2 = nn.Sequential(nn.Conv2d(64, 128, 3, 1, 'same'), nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2))
        self.layer3 = nn.Sequential(nn.Conv2d(128, 256, 3, 1, 'same'), nn.BatchNorm2d(256), nn.ReLU(), nn.AdaptiveAvgPool2d((2, 2)))
        self.flatten = nn.Flatten()
        self.classifier = nn.Sequential(
            nn.Linear(1024 + 256, 512), nn.BatchNorm1d(512), nn.ReLU(), nn.Dropout(0.4), nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        cnn_features = self.flatten(self.layer3(self.layer2(self.layer1(img))))
        return self.classifier(torch.cat([cnn_features, mlbp], dim=1))

def predict_custom_enhanced():
    if not os.path.exists('best_custom_enhanced.pt'):
        print("[ERROR] 'best_custom_enhanced.pt' not found!"); return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = Enhanced3LayerCNN(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_custom_enhanced.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    print("\n[READY] Please upload an iron ore pellet image.")
    uploaded = files.upload()

    for filename, file_data in uploaded.items():
        image_pil = Image.open(io.BytesIO(file_data)).convert('RGB')
        img_tensor = tf(image_pil).unsqueeze(0).to(device)

        img_cv = cv2.resize(cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_tensor = torch.tensor(compute_mlbp(img_cv), dtype=torch.float32).unsqueeze(0).to(device)

        with torch.no_grad():
            raw_logits = model(img_tensor, mlbp_tensor)

            # EXPLICIT SOFTMAX
            probabilities = nn.Softmax(dim=1)(raw_logits)[0]
            conf, pred_idx = torch.max(probabilities, 0)

        plt.figure(figsize=(6, 6))
        plt.imshow(image_pil)
        plt.title(f"Prediction: {CLASSES[pred_idx.item()]}\n(Softmax Confidence: {conf.item() * 100:.2f}%)", color='green', fontweight='bold')
        plt.axis('off'); plt.show()

        print("\n--- Final Softmax Output ---")
        for i, c in enumerate(CLASSES): print(f"{c}: {probabilities[i].item() * 100:.2f}%")

predict_custom_enhanced()

