# -*- coding: utf-8 -*-
"""IronOreMoistureContent(U-Net).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18M2StlXJ1WXEQGtEobOj6FFZXouV4ClE
"""

# =====================================================================================
# CELL 1: U-SHAPED ARCHITECTURE PIPELINE
# Architecture: 3 Encoders + 3 Decoders (U-Net style) + MLBP Fusion -> Classification
# =====================================================================================

import os, cv2, zipfile, shutil
import numpy as np, matplotlib.pyplot as plt, seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

try: from google.colab import files; IN_COLAB = True
except ImportError: IN_COLAB = False

ZIP_PATH, BASE_DIR, SPLIT_DIR = "iron_ore_pellets.zip", "dataset_raw", "dataset"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. DATASET & MLBP
# -------------------------------------------------------------------------
def prepare_dataset_hierarchy():
    if not os.path.exists(ZIP_PATH): raise ValueError(f"[ERROR] '{ZIP_PATH}' not found!")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    os.makedirs(BASE_DIR)
    with zipfile.ZipFile(ZIP_PATH, 'r') as z: z.extractall(BASE_DIR)

    all_files, labels = [], []
    norm_classes = {c.lower().replace(" ", ""): c for c in CLASSES}
    for root, dirs, files in os.walk(BASE_DIR):
        p_norm = os.path.basename(root).lower().replace(" ", "")
        imgs = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]
        if p_norm in norm_classes:
            all_files.extend([os.path.join(root, f) for f in imgs])
            labels.extend([norm_classes[p_norm]] * len(imgs))

    X_tr, X_temp, y_tr, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_te, y_val, y_te = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)
    for split, paths, lbls in zip(['train', 'val', 'test'], [X_tr, X_val, X_te], [y_tr, y_val, y_te]):
        for cls in CLASSES: os.makedirs(os.path.join(SPLIT_DIR, split, cls), exist_ok=True)
        for path, cls in zip(paths, lbls): shutil.copy2(path, os.path.join(SPLIT_DIR, split, cls, os.path.basename(path)))

def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    mean_tau = cv2.filter2D(img_float, -1, np.ones((3, 3), np.float32) / 9.0)
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)
    dx, dy = [-1,  0,  1, 1, 1, 0, -1, -1], [-1, -1, -1, 0, 1, 1,  1,  0]
    for i in range(8):
        neighbor = padded[1+dy[i]:1+dy[i]+h, 1+dx[i]:1+dx[i]+w]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)
    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    return (hist.astype(np.float32) / (hist.sum() + 1e-6))

class DualStreamDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir, self.transform = Path(root_dir), transform
        self.paths, self.labels = [], []
        for idx, cls in enumerate(CLASSES):
            d = self.root_dir / cls
            if d.exists():
                for f in os.listdir(d):
                    if f.lower().endswith(('.jpg', '.png', '.jpeg', '.bmp')):
                        self.paths.append(str(d / f)); self.labels.append(idx)

    def __len__(self): return len(self.paths)
    def __getitem__(self, idx):
        img_pil = Image.open(self.paths[idx]).convert('RGB')
        img_tensor = self.transform(img_pil)
        img_cv = cv2.resize(cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_tensor = torch.tensor(compute_mlbp(img_cv), dtype=torch.float32)
        return img_tensor, mlbp_tensor, self.labels[idx]

train_tf = transforms.Compose([transforms.Resize((224, 224)), transforms.RandomHorizontalFlip(), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
test_tf = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

# -------------------------------------------------------------------------
# 2. U-SHAPED CLASSIFICATION ARCHITECTURE (3 ENCODERS, 3 DECODERS)
# -------------------------------------------------------------------------
class DoubleConv(nn.Module):
    """Helper block containing Two 3x3 Convolutions with Padding"""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
    def forward(self, x): return self.conv(x)

class UShapedClassifier(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()

        # --- 3 ENCODERS (Downsampling) ---
        self.enc1 = DoubleConv(3, 64)
        self.pool1 = nn.MaxPool2d(2)

        self.enc2 = DoubleConv(64, 128)
        self.pool2 = nn.MaxPool2d(2)

        self.enc3 = DoubleConv(128, 256)
        self.pool3 = nn.MaxPool2d(2)

        # --- BOTTLENECK ---
        self.bottleneck = DoubleConv(256, 512)

        # --- 3 DECODERS (Upsampling + Skip Connections) ---
        self.up1 = nn.ConvTranspose2d(512, 256, kernel_size=2, stride=2)
        self.dec1 = DoubleConv(512, 256) # 256 (upsampled) + 256 (skip)

        self.up2 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.dec2 = DoubleConv(256, 128) # 128 (upsampled) + 128 (skip)

        self.up3 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2)
        self.dec3 = DoubleConv(128, 64)  # 64 (upsampled) + 64 (skip)

        # --- FEATURE PROJECTION & CLASSIFICATION ---
        # Compress the final high-res 64-channel 224x224 image into a dense vector
        self.feature_proj = nn.Sequential(
            nn.Conv2d(64, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512), nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten()
        )

        # Classifier (512 U-Shape features + 256 MLBP features = 768)
        self.classifier = nn.Sequential(
            nn.Linear(768, 512), nn.BatchNorm1d(512), nn.ReLU(inplace=True), nn.Dropout(0.4), nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        # Encoders Path
        e1 = self.enc1(img)            # [B, 64, 224, 224]
        e2 = self.enc2(self.pool1(e1)) # [B, 128, 112, 112]
        e3 = self.enc3(self.pool2(e2)) # [B, 256, 56, 56]

        # Bottleneck
        b = self.bottleneck(self.pool3(e3)) # [B, 512, 28, 28]

        # Decoders Path (with skip connections)
        d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1)) # [B, 256, 56, 56]
        d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1)) # [B, 128, 112, 112]
        d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1)) # [B, 64, 224, 224]

        # Global Feature Pooling
        u_features = self.feature_proj(d3)

        # Fuse and Classify
        return self.classifier(torch.cat([u_features, mlbp], dim=1))

# -------------------------------------------------------------------------
# 3. TRAINING & EVALUATION
# -------------------------------------------------------------------------
def train_and_evaluate():
    prepare_dataset_hierarchy()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Training U-Shaped Classifier on: {device}")

    # Batch size 16 to safely fit the U-Net skip connection memory in VRAM
    tr_loader = DataLoader(DualStreamDataset(os.path.join(SPLIT_DIR, 'train'), train_tf), batch_size=16, shuffle=True)
    val_loader = DataLoader(DualStreamDataset(os.path.join(SPLIT_DIR, 'val'), test_tf), batch_size=16)
    te_loader = DataLoader(DualStreamDataset(os.path.join(SPLIT_DIR, 'test'), test_tf), batch_size=16)

    model = UShapedClassifier(len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-3)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)

    best_val_loss = float('inf')
    epochs = 30

    for epoch in range(epochs):
        model.train()
        tr_loss = 0.0
        for imgs, mlbps, lbls in tr_loader:
            imgs, mlbps, lbls = imgs.to(device), mlbps.to(device), lbls.to(device)
            optimizer.zero_grad()
            loss = criterion(model(imgs, mlbps), lbls)
            loss.backward()
            optimizer.step()
            tr_loss += loss.item() * imgs.size(0)

        tr_loss /= len(tr_loader.dataset)

        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, mlbps, lbls in val_loader:
                imgs, mlbps, lbls = imgs.to(device), mlbps.to(device), lbls.to(device)
                out = model(imgs, mlbps)
                val_loss += criterion(out, lbls).item() * imgs.size(0)
                all_preds.extend(torch.max(out, 1)[1].cpu().numpy()); all_labels.extend(lbls.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        scheduler.step(val_loss)
        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {tr_loss:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {accuracy_score(all_labels, all_preds):.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_unet_model.pt')

    print("\n[INFO] Evaluating on Test Split...")
    model.load_state_dict(torch.load('best_unet_model.pt', map_location=device, weights_only=True))
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for imgs, mlbps, lbls in te_loader:
            imgs, mlbps, lbls = imgs.to(device), mlbps.to(device), lbls.to(device)
            all_preds.extend(torch.max(model(imgs, mlbps), 1)[1].cpu().numpy()); all_labels.extend(lbls.cpu().numpy())

    print("\n--- Classification Report (U-Shaped Network) ---")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, zero_division=0))

    plt.figure(figsize=(8, 6))
    sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('U-Shaped Architecture - Confusion Matrix')
    plt.xlabel('Predicted Label'); plt.ylabel('True Label'); plt.tight_layout(); plt.show()

    if IN_COLAB: files.download('best_unet_model.pt')

if __name__ == "__main__":
    train_and_evaluate()

# =====================================================================================
# CELL 2: INTERACTIVE INFERENCE (U-SHAPED NETWORK)
# =====================================================================================

import os, cv2, torch, io, matplotlib.pyplot as plt, numpy as np
import torch.nn as nn
from PIL import Image
from torchvision import transforms
from google.colab import files

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    mean_tau = cv2.filter2D(image_cv_gray.astype(np.float32), -1, np.ones((3, 3), np.float32) / 9.0)
    padded = np.pad(image_cv_gray.astype(np.float32), 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)
    dx, dy = [-1,  0,  1, 1, 1, 0, -1, -1], [-1, -1, -1, 0, 1, 1,  1,  0]
    for i in range(8):
        neighbor = padded[1+dy[i]:1+dy[i]+h, 1+dx[i]:1+dx[i]+w]
        mlbp |= ((neighbor >= mean_tau).astype(np.uint8) << i)
    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    return (hist.astype(np.float32) / (hist.sum() + 1e-6))

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(nn.Conv2d(in_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True),
                                  nn.Conv2d(out_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True))
    def forward(self, x): return self.conv(x)

class UShapedClassifier(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.enc1, self.pool1 = DoubleConv(3, 64), nn.MaxPool2d(2)
        self.enc2, self.pool2 = DoubleConv(64, 128), nn.MaxPool2d(2)
        self.enc3, self.pool3 = DoubleConv(128, 256), nn.MaxPool2d(2)
        self.bottleneck = DoubleConv(256, 512)
        self.up1, self.dec1 = nn.ConvTranspose2d(512, 256, 2, 2), DoubleConv(512, 256)
        self.up2, self.dec2 = nn.ConvTranspose2d(256, 128, 2, 2), DoubleConv(256, 128)
        self.up3, self.dec3 = nn.ConvTranspose2d(128, 64, 2, 2), DoubleConv(128, 64)
        self.feature_proj = nn.Sequential(nn.Conv2d(64, 512, 3, padding=1), nn.BatchNorm2d(512), nn.ReLU(), nn.AdaptiveAvgPool2d((1, 1)), nn.Flatten())
        self.classifier = nn.Sequential(nn.Linear(768, 512), nn.BatchNorm1d(512), nn.ReLU(), nn.Dropout(0.4), nn.Linear(512, num_classes))

    def forward(self, img, mlbp):
        e1 = self.enc1(img)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))
        b = self.bottleneck(self.pool3(e3))
        d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1))
        return self.classifier(torch.cat([self.feature_proj(d3), mlbp], dim=1))

def predict_unet():
    if not os.path.exists('best_unet_model.pt'):
        print("[ERROR] 'best_unet_model.pt' not found!"); return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = UShapedClassifier(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_unet_model.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    print("\n[READY] Please upload an iron ore pellet image.")
    uploaded = files.upload()

    for filename, file_data in uploaded.items():
        image_pil = Image.open(io.BytesIO(file_data)).convert('RGB')
        img_tensor = tf(image_pil).unsqueeze(0).to(device)
        img_cv = cv2.resize(cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY), (224, 224))
        mlbp_tensor = torch.tensor(compute_mlbp(img_cv), dtype=torch.float32).unsqueeze(0).to(device)

        with torch.no_grad():
            raw_logits = model(img_tensor, mlbp_tensor)
            probabilities = nn.Softmax(dim=1)(raw_logits)[0]
            conf, pred_idx = torch.max(probabilities, 0)

        plt.figure(figsize=(6, 6))
        plt.imshow(image_pil)
        plt.title(f"U-Net Prediction: {CLASSES[pred_idx.item()]}\n(Softmax Confidence: {conf.item() * 100:.2f}%)", color='blue', fontweight='bold')
        plt.axis('off'); plt.show()

        print("\n--- Final Softmax Output ---")
        for i, c in enumerate(CLASSES): print(f"{c}: {probabilities[i].item() * 100:.2f}%")

predict_unet()

# =====================================================================================
# CELL 3: FPS BENCHMARKING (U-SHAPED NETWORK)
# =====================================================================================

import time, torch, cv2, numpy as np
from PIL import Image
from torchvision import transforms

def benchmark_unet(iterations=100):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Benchmarking U-Shaped Classifier on: {device.type.upper()}")

    if not os.path.exists('best_unet_model.pt'):
        print("[ERROR] 'best_unet_model.pt' not found."); return

    model = UShapedClassifier(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_unet_model.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
    dummy_image = Image.fromarray(np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8))

    print("[INFO] Warming up GPU (10 passes)...")
    for _ in range(10):
        i_tensor = tf(dummy_image).unsqueeze(0).to(device)
        i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
        m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)
        with torch.no_grad(): _ = model(i_tensor, m_tensor)

    print(f"[INFO] Running {iterations} passes through 3 Encoders / 3 Decoders...\n")

    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            i_t = tf(dummy_image).unsqueeze(0).to(device)
            i_c = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
            m_t = torch.tensor(compute_mlbp(i_c), dtype=torch.float32).unsqueeze(0).to(device)
            _ = model(i_t, m_t)

            if device.type == 'cuda': torch.cuda.synchronize()
            pipeline_times.append((time.perf_counter() - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    print("="*60)
    print("         U-SHAPED CLASSIFIER SPEED REPORT")
    print("="*60)
    print(f"Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print(f"Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)

benchmark_unet()