# -*- coding: utf-8 -*-
"""Segmented U-Net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1act3sKb0Mh75QgRRF2RM125-iFCLyGap
"""

# =====================================================================================
# CELL 1: TURBOCHARGED QUADRANT U-NET (LOSS, ACCURACY, & CONFUSION MATRIX PLOTS)
# Upgrades: Mixed Precision (AMP), Lite Channels, Early Stopping, pin_memory
# =====================================================================================

import os, zipfile, shutil
import numpy as np, matplotlib.pyplot as plt, seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from torch.cuda.amp import autocast, GradScaler

try: from google.colab import files; IN_COLAB = True
except ImportError: IN_COLAB = False

ZIP_PATH, BASE_DIR, SPLIT_DIR = "iron_ore_pellets.zip", "dataset_raw", "dataset_quad_unet"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

# -------------------------------------------------------------------------
# 1. PREPROCESSING: RESIZE & SEGMENT PIPELINE
# -------------------------------------------------------------------------
def process_and_slice_images(file_paths, labels, split_name):
    for cls in CLASSES: os.makedirs(os.path.join(SPLIT_DIR, split_name, cls), exist_ok=True)
    for path, cls in zip(file_paths, labels):
        try:
            img = Image.open(path).convert('RGB').resize((656, 480))
            quadrants = [img.crop((0,0,328,240)), img.crop((328,0,656,240)), img.crop((0,240,328,480)), img.crop((328,240,656,480))]
            base = os.path.splitext(os.path.basename(path))[0]
            for i, q_img in enumerate(quadrants): q_img.save(os.path.join(SPLIT_DIR, split_name, cls, f"{base}_q{i}.jpg"))
        except Exception: pass

def prepare_quadrant_dataset():
    if not os.path.exists(ZIP_PATH): raise ValueError(f"[ERROR] '{ZIP_PATH}' not found!")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    with zipfile.ZipFile(ZIP_PATH, 'r') as z: z.extractall(BASE_DIR)
    all_files, labels = [], []
    norm_cls = {c.lower().replace(" ", ""): c for c in CLASSES}
    for root, dirs, files in os.walk(BASE_DIR):
        p_norm = os.path.basename(root).lower().replace(" ", "")
        imgs = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]
        if p_norm in norm_cls:
            all_files.extend([os.path.join(root, f) for f in imgs]); labels.extend([norm_cls[p_norm]] * len(imgs))
    X_tr, X_temp, y_tr, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    X_val, X_te, y_val, y_te = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)
    process_and_slice_images(X_tr, y_tr, 'train')
    process_and_slice_images(X_val, y_val, 'val')
    process_and_slice_images(X_te, y_te, 'test')

train_tf = transforms.Compose([transforms.RandomHorizontalFlip(), transforms.RandomVerticalFlip(), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
test_tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

class QuadrantDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir, self.transform = Path(root_dir), transform
        self.paths, self.labels = [], []
        for idx, cls in enumerate(CLASSES):
            d = self.root_dir / cls
            if d.exists():
                for f in os.listdir(d):
                    if f.lower().endswith('.jpg'): self.paths.append(str(d/f)); self.labels.append(idx)
    def __len__(self): return len(self.paths)
    def __getitem__(self, idx): return self.transform(Image.open(self.paths[idx]).convert('RGB')), self.labels[idx]

# -------------------------------------------------------------------------
# 2. FAST U-NET ARCHITECTURE
# -------------------------------------------------------------------------
class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
    def forward(self, x): return self.conv(x)

class FastQuadrantUNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.enc1 = DoubleConv(3, 32);   self.pool1 = nn.MaxPool2d(2)
        self.enc2 = DoubleConv(32, 64);  self.pool2 = nn.MaxPool2d(2)
        self.enc3 = DoubleConv(64, 128); self.pool3 = nn.MaxPool2d(2)
        self.bottleneck = DoubleConv(128, 256)

        self.up1 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2); self.dec1 = DoubleConv(256, 128)
        self.up2 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2);  self.dec2 = DoubleConv(128, 64)
        self.up3 = nn.ConvTranspose2d(64, 32, kernel_size=2, stride=2);   self.dec3 = DoubleConv(64, 32)

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d((2, 2)), nn.Flatten(),
            nn.Linear(128, 256), nn.BatchNorm1d(256), nn.ReLU(inplace=True),
            nn.Dropout(0.4), nn.Linear(256, num_classes)
        )

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))
        b = self.bottleneck(self.pool3(e3))
        d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1))
        return self.classifier(d3)

# -------------------------------------------------------------------------
# 3. TRAINING PIPELINE (TRACKS LOSS & ACCURACY)
# -------------------------------------------------------------------------
def train_and_evaluate():
    prepare_quadrant_dataset()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Fast U-Net Training Initialized on: {device}")

    tr_loader = DataLoader(QuadrantDataset(os.path.join(SPLIT_DIR, 'train'), train_tf), batch_size=32, shuffle=True, pin_memory=True, num_workers=2)
    val_loader = DataLoader(QuadrantDataset(os.path.join(SPLIT_DIR, 'val'), test_tf), batch_size=32, pin_memory=True, num_workers=2)
    te_loader = DataLoader(QuadrantDataset(os.path.join(SPLIT_DIR, 'test'), test_tf), batch_size=32)

    model = FastQuadrantUNet(len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=2)
    scaler = GradScaler()

    best_val_loss = float('inf')
    epochs = 30
    patience_counter = 0
    patience_limit = 5

    # Tracking lists for our plots
    history_train_loss, history_val_loss = [], []
    history_train_acc, history_val_acc = [], []

    for epoch in range(epochs):
        # --- TRAINING PHASE ---
        model.train()
        tr_loss = 0.0
        train_preds, train_labels = [], []

        for imgs, lbls in tr_loader:
            imgs, lbls = imgs.to(device, non_blocking=True), lbls.to(device, non_blocking=True)
            optimizer.zero_grad()

            with autocast():
                out = model(imgs)
                loss = criterion(out, lbls)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            tr_loss += loss.item() * imgs.size(0)

            # Track Training Accuracy dynamically
            _, preds = torch.max(out, 1)
            train_preds.extend(preds.detach().cpu().numpy())
            train_labels.extend(lbls.detach().cpu().numpy())

        tr_loss /= len(tr_loader.dataset)
        tr_acc = accuracy_score(train_labels, train_preds)

        # --- VALIDATION PHASE ---
        model.eval()
        val_loss, all_preds, all_labels = 0.0, [], []
        with torch.no_grad():
            for imgs, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                with autocast():
                    out = model(imgs)
                    loss = criterion(out, lbls)
                val_loss += loss.item() * imgs.size(0)
                all_preds.extend(torch.max(out, 1)[1].cpu().numpy()); all_labels.extend(lbls.cpu().numpy())

        val_loss /= len(val_loader.dataset)
        val_acc = accuracy_score(all_labels, all_preds)
        scheduler.step(val_loss)

        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {tr_loss:.4f} - Train Acc: {tr_acc:.4f} | Val Loss: {val_loss:.4f} - Val Acc: {val_acc:.4f}")

        # Append to histories
        history_train_loss.append(tr_loss); history_val_loss.append(val_loss)
        history_train_acc.append(tr_acc); history_val_acc.append(val_acc)

        # Early Stopping
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
            torch.save(model.state_dict(), 'best_fast_unet.pt')
        else:
            patience_counter += 1
            if patience_counter >= patience_limit:
                print(f"\n[INFO] Early Stopping Triggered! Validation loss stopped improving.")
                break

    # ==========================================================
    # VISUALIZATION PLOTS
    # ==========================================================

    # 1. Plot: Training vs Validation Loss
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, len(history_train_loss)+1), history_train_loss, label='Training Loss', marker='o', color='royalblue')
    plt.plot(range(1, len(history_val_loss)+1), history_val_loss, label='Validation Loss', marker='s', color='darkorange')
    plt.title('Training Loss vs Validation Loss (Fast U-Net)', fontsize=14, fontweight='bold')
    plt.xlabel('Epochs', fontsize=12); plt.ylabel('Cross-Entropy Loss', fontsize=12)
    plt.legend(fontsize=12); plt.grid(True, linestyle='--', alpha=0.7); plt.tight_layout()
    plt.show()

    # 2. Plot: Training vs Validation Accuracy
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, len(history_train_acc)+1), history_train_acc, label='Training Accuracy', marker='o', color='forestgreen')
    plt.plot(range(1, len(history_val_acc)+1), history_val_acc, label='Validation Accuracy', marker='s', color='mediumorchid')
    plt.title('Training Accuracy vs Validation Accuracy (Fast U-Net)', fontsize=14, fontweight='bold')
    plt.xlabel('Epochs', fontsize=12); plt.ylabel('Accuracy', fontsize=12)
    plt.legend(fontsize=12); plt.grid(True, linestyle='--', alpha=0.7); plt.tight_layout()
    plt.show()

    # Evaluation on Test Split
    print("\n[INFO] Evaluating on 328x240 Test Quadrants...")
    model.load_state_dict(torch.load('best_fast_unet.pt', map_location=device, weights_only=True))
    model.eval()
    test_preds, test_labels = [], []
    with torch.no_grad():
        for imgs, lbls in te_loader:
            test_preds.extend(torch.max(model(imgs.to(device)), 1)[1].cpu().numpy()); test_labels.extend(lbls.numpy())

    print("\n--- Classification Report (Fast U-Net) ---")
    print(classification_report(test_labels, test_preds, target_names=CLASSES, zero_division=0))

    # 3. Plot: Confusion Matrix
    cm = confusion_matrix(test_labels, test_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('Fast U-Net - Confusion Matrix', fontsize=14, fontweight='bold')
    plt.xlabel('Predicted Label', fontsize=12); plt.ylabel('True Label', fontsize=12)
    plt.tight_layout(); plt.show()

    if IN_COLAB: files.download('best_fast_unet.pt')

if __name__ == "__main__":
    train_and_evaluate()

# =====================================================================================
# CELL 2: INTERACTIVE INFERENCE (FAST U-NET ENSEMBLE)
# =====================================================================================

import os, torch, io, matplotlib.pyplot as plt, numpy as np
import torch.nn as nn
from PIL import Image
from torchvision import transforms
from google.colab import files

CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(nn.Conv2d(in_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True),
                                  nn.Conv2d(out_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True))
    def forward(self, x): return self.conv(x)

class FastQuadrantUNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.enc1 = DoubleConv(3, 32);   self.pool1 = nn.MaxPool2d(2)
        self.enc2 = DoubleConv(32, 64);  self.pool2 = nn.MaxPool2d(2)
        self.enc3 = DoubleConv(64, 128); self.pool3 = nn.MaxPool2d(2)
        self.bottleneck = DoubleConv(128, 256)
        self.up1 = nn.ConvTranspose2d(256, 128, 2, 2); self.dec1 = DoubleConv(256, 128)
        self.up2 = nn.ConvTranspose2d(128, 64, 2, 2);  self.dec2 = DoubleConv(128, 64)
        self.up3 = nn.ConvTranspose2d(64, 32, 2, 2);   self.dec3 = DoubleConv(64, 32)
        self.classifier = nn.Sequential(nn.AdaptiveAvgPool2d((2, 2)), nn.Flatten(), nn.Linear(128, 256), nn.BatchNorm1d(256), nn.ReLU(inplace=True), nn.Dropout(0.4), nn.Linear(256, num_classes))

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))
        b = self.bottleneck(self.pool3(e3))
        d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1))
        return self.classifier(d3)

def predict_fast_unet():
    if not os.path.exists('best_fast_unet.pt'):
        print("[ERROR] 'best_fast_unet.pt' not found!"); return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = FastQuadrantUNet(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_fast_unet.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    print("\n[READY] Please upload a full-size iron ore pellet image.")
    uploaded = files.upload()

    for filename, file_data in uploaded.items():
        original_img = Image.open(io.BytesIO(file_data)).convert('RGB')
        img_resized = original_img.resize((656, 480))
        quads = [img_resized.crop((0, 0, 328, 240)), img_resized.crop((328, 0, 656, 240)), img_resized.crop((0, 240, 328, 480)), img_resized.crop((328, 240, 656, 480))]
        batch_tensors = torch.stack([tf(q) for q in quads]).to(device)

        with torch.no_grad():
            from torch.cuda.amp import autocast
            with autocast():
                raw_logits = model(batch_tensors)
                quad_probs = nn.Softmax(dim=1)(raw_logits)
            final_probs = torch.mean(quad_probs, dim=0)
            conf, pred_idx = torch.max(final_probs, 0)

        plt.figure(figsize=(6, 6))
        plt.imshow(original_img)
        plt.title(f"Fast U-Net Prediction: {CLASSES[pred_idx.item()]}\n(Average Softmax Confidence: {conf.item() * 100:.2f}%)", color='purple', fontweight='bold')
        plt.axis('off'); plt.show()

        print("\n--- Final Output ---")
        for i, c in enumerate(CLASSES): print(f"{c}: {final_probs[i].item() * 100:.2f}%")

predict_fast_unet()

# =====================================================================================
# CELL 3: FPS BENCHMARKING (FAST U-NET)
# =====================================================================================

import time, torch, numpy as np
from PIL import Image
from torchvision import transforms
import torch.nn as nn
from torch.cuda.amp import autocast

def benchmark_fast_unet(iterations=200):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Benchmarking Fast U-Net Pipeline on: {device.type.upper()}")

    if not os.path.exists('best_fast_unet.pt'):
        print("[ERROR] 'best_fast_unet.pt' not found."); return

    model = FastQuadrantUNet(len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best_fast_unet.pt', map_location=device, weights_only=True))
    model.eval()

    tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
    dummy_image = Image.fromarray(np.random.randint(0, 255, (494, 659, 3), dtype=np.uint8))

    print("[INFO] Warming up GPU with Mixed Precision...")
    for _ in range(10):
        dummy_batch = torch.randn(4, 3, 240, 328).to(device)
        with torch.no_grad():
            with autocast(): _ = model(dummy_batch)

    print(f"[INFO] Running {iterations} iterations on End-to-End Pipeline...\n")

    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            img_res = dummy_image.resize((656, 480))
            quads = [img_res.crop((0,0,328,240)), img_res.crop((328,0,656,240)), img_res.crop((0,240,328,480)), img_res.crop((328,240,656,480))]
            batch_tensors = torch.stack([tf(q) for q in quads]).to(device)

            with autocast(): # AMP processing
                probs = torch.mean(nn.Softmax(dim=1)(model(batch_tensors)), dim=0)

            if device.type == 'cuda': torch.cuda.synchronize()
            pipeline_times.append((time.perf_counter() - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    print("="*60)
    print("         FAST U-NET SPEED REPORT")
    print("="*60)
    print(f"Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print(f"Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)

benchmark_fast_unet()